DATABASE:
  HOST: ${DATABASE_HOST}
  PORT: ${DATABASE_PORT}
  NAME: ${DATABASE_NAME}
  USERNAME: ${DATABASE_USERNAME}
  PASSWORD: ${DATABASE_PASSWORD}

JWT:
  HEADER: ${JWT_HEADER}
  SECRET: ${JWT_SECRET}
  TOKEN-VALIDITY-IN-SECONDS: ${JWT_JWT.TOKEN-VALIDITY-IN-SECONDS}
  SECRET2: ${JWT_SECRET2}
  TOKEN-VALIDITY-IN-SECONDS2: ${JWT_TOKEN-VALIDITY-IN-SECONDS2}