name: Apply PR Template to Develop

on:
  pull_request:
    branches:
      - develop
    types: [opened, edited]
jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Apply PR Template
      run: |
        # PR 템플릿 파일 내용을 읽어옵니다.
        TEMPLATE=$(cat .github/pull_request_template.md)
        
        # GitHub API를 사용하여 PR의 본문을 업데이트합니다.
        curl -X PATCH \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Content-Type: application/json" \
             -d "{\"body\": \"$TEMPLATE\"}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
